/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_agent (void)
{
  GtkWidget *agent;
  GtkWidget *fixed1;
  GtkWidget *offres;
  GtkWidget *voles;
  GtkWidget *hotels;
  GtkWidget *location_de_voiture;
  GtkWidget *mon_compte;
  GtkWidget *g_de_res;
  GtkWidget *g_de_cl;
  GtkWidget *g_de_off;
  GtkWidget *g_de_rec;
  GtkWidget *retournerag;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;

  agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (agent), _("agent"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (agent), fixed1);

  offres = gtk_button_new_with_mnemonic (_("offres"));
  gtk_widget_show (offres);
  gtk_fixed_put (GTK_FIXED (fixed1), offres, 16, 16);
  gtk_widget_set_size_request (offres, 74, 29);

  voles = gtk_button_new_with_mnemonic (_("voles"));
  gtk_widget_show (voles);
  gtk_fixed_put (GTK_FIXED (fixed1), voles, 104, 16);
  gtk_widget_set_size_request (voles, 74, 29);

  hotels = gtk_button_new_with_mnemonic (_("hotels"));
  gtk_widget_show (hotels);
  gtk_fixed_put (GTK_FIXED (fixed1), hotels, 200, 16);
  gtk_widget_set_size_request (hotels, 74, 29);

  location_de_voiture = gtk_button_new_with_mnemonic (_("location de voiture"));
  gtk_widget_show (location_de_voiture);
  gtk_fixed_put (GTK_FIXED (fixed1), location_de_voiture, 296, 16);
  gtk_widget_set_size_request (location_de_voiture, 144, 29);

  mon_compte = gtk_button_new_with_mnemonic (_("mon compte"));
  gtk_widget_show (mon_compte);
  gtk_fixed_put (GTK_FIXED (fixed1), mon_compte, 464, 16);
  gtk_widget_set_size_request (mon_compte, 104, 29);

  g_de_res = gtk_button_new_with_mnemonic (_("gestion de reservation"));
  gtk_widget_show (g_de_res);
  gtk_fixed_put (GTK_FIXED (fixed1), g_de_res, 192, 176);
  gtk_widget_set_size_request (g_de_res, 224, 29);

  g_de_cl = gtk_button_new_with_mnemonic (_("gestion de clients"));
  gtk_widget_show (g_de_cl);
  gtk_fixed_put (GTK_FIXED (fixed1), g_de_cl, 192, 96);
  gtk_widget_set_size_request (g_de_cl, 224, 29);

  g_de_off = gtk_button_new_with_mnemonic (_("gestion des offres"));
  gtk_widget_show (g_de_off);
  gtk_fixed_put (GTK_FIXED (fixed1), g_de_off, 192, 216);
  gtk_widget_set_size_request (g_de_off, 224, 29);

  g_de_rec = gtk_button_new_with_mnemonic (_("gestion de reclamation"));
  gtk_widget_show (g_de_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), g_de_rec, 192, 136);
  gtk_widget_set_size_request (g_de_rec, 224, 29);

  retournerag = gtk_button_new ();
  gtk_widget_show (retournerag);
  gtk_fixed_put (GTK_FIXED (fixed1), retournerag, 8, 72);
  gtk_widget_set_size_request (retournerag, 96, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (retournerag), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) g_de_res, "clicked",
                    G_CALLBACK (on_g_de_res_clicked),
                    NULL);
  g_signal_connect ((gpointer) g_de_cl, "clicked",
                    G_CALLBACK (on_g_de_cl_clicked),
                    NULL);
  g_signal_connect ((gpointer) g_de_off, "clicked",
                    G_CALLBACK (on_g_de_off_clicked),
                    NULL);
  g_signal_connect ((gpointer) g_de_rec, "clicked",
                    G_CALLBACK (on_g_de_rec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (agent, agent, "agent");
  GLADE_HOOKUP_OBJECT (agent, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (agent, offres, "offres");
  GLADE_HOOKUP_OBJECT (agent, voles, "voles");
  GLADE_HOOKUP_OBJECT (agent, hotels, "hotels");
  GLADE_HOOKUP_OBJECT (agent, location_de_voiture, "location_de_voiture");
  GLADE_HOOKUP_OBJECT (agent, mon_compte, "mon_compte");
  GLADE_HOOKUP_OBJECT (agent, g_de_res, "g_de_res");
  GLADE_HOOKUP_OBJECT (agent, g_de_cl, "g_de_cl");
  GLADE_HOOKUP_OBJECT (agent, g_de_off, "g_de_off");
  GLADE_HOOKUP_OBJECT (agent, g_de_rec, "g_de_rec");
  GLADE_HOOKUP_OBJECT (agent, retournerag, "retournerag");
  GLADE_HOOKUP_OBJECT (agent, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (agent, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (agent, image2, "image2");
  GLADE_HOOKUP_OBJECT (agent, label2, "label2");

  return agent;
}

GtkWidget*
create_gestion_de_clients (void)
{
  GtkWidget *gestion_de_clients;
  GtkWidget *fixed2;
  GtkWidget *offres;
  GtkWidget *voles;
  GtkWidget *hotels;
  GtkWidget *location_de_voiture;
  GtkWidget *mon_compte;
  GtkWidget *modfier_client;
  GtkWidget *button12;
  GtkWidget *retournergdc;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;

  gestion_de_clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_de_clients), _("gestion de clients"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_de_clients), fixed2);

  offres = gtk_button_new_with_mnemonic (_("offres"));
  gtk_widget_show (offres);
  gtk_fixed_put (GTK_FIXED (fixed2), offres, 24, 16);
  gtk_widget_set_size_request (offres, 74, 29);

  voles = gtk_button_new_with_mnemonic (_("voles"));
  gtk_widget_show (voles);
  gtk_fixed_put (GTK_FIXED (fixed2), voles, 120, 16);
  gtk_widget_set_size_request (voles, 74, 29);

  hotels = gtk_button_new_with_mnemonic (_("hotels"));
  gtk_widget_show (hotels);
  gtk_fixed_put (GTK_FIXED (fixed2), hotels, 216, 16);
  gtk_widget_set_size_request (hotels, 74, 29);

  location_de_voiture = gtk_button_new_with_mnemonic (_("location de voiture"));
  gtk_widget_show (location_de_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), location_de_voiture, 304, 16);
  gtk_widget_set_size_request (location_de_voiture, 152, 29);

  mon_compte = gtk_button_new_with_mnemonic (_("mon compte"));
  gtk_widget_show (mon_compte);
  gtk_fixed_put (GTK_FIXED (fixed2), mon_compte, 472, 16);
  gtk_widget_set_size_request (mon_compte, 96, 29);

  modfier_client = gtk_button_new_with_mnemonic (_("modifier client"));
  gtk_widget_show (modfier_client);
  gtk_fixed_put (GTK_FIXED (fixed2), modfier_client, 208, 256);
  gtk_widget_set_size_request (modfier_client, 224, 32);

  button12 = gtk_button_new_with_mnemonic (_("chercher client"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed2), button12, 208, 192);
  gtk_widget_set_size_request (button12, 224, 32);

  retournergdc = gtk_button_new ();
  gtk_widget_show (retournergdc);
  gtk_fixed_put (GTK_FIXED (fixed2), retournergdc, 56, 80);
  gtk_widget_set_size_request (retournergdc, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (retournergdc), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retournergdc, "clicked",
                    G_CALLBACK (on_retournergdc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_de_clients, gestion_de_clients, "gestion_de_clients");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, offres, "offres");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, voles, "voles");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, hotels, "hotels");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, location_de_voiture, "location_de_voiture");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, mon_compte, "mon_compte");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, modfier_client, "modfier_client");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, button12, "button12");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, retournergdc, "retournergdc");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_de_clients, label1, "label1");

  return gestion_de_clients;
}

GtkWidget*
create_gestion_des_reclamations (void)
{
  GtkWidget *gestion_des_reclamations;
  GtkWidget *fixed3;
  GtkWidget *button24;
  GtkWidget *button25;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkWidget *button30;
  GtkWidget *ajouter_des_reclamations_;
  GtkWidget *button33;
  GtkWidget *button32;
  GtkWidget *retournergdr;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;

  gestion_des_reclamations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_reclamations), _("gestion des reclamations"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (gestion_des_reclamations), fixed3);

  button24 = gtk_button_new_with_mnemonic (_("offres"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed3), button24, 24, 16);
  gtk_widget_set_size_request (button24, 74, 29);

  button25 = gtk_button_new_with_mnemonic (_("voles"));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed3), button25, 120, 16);
  gtk_widget_set_size_request (button25, 74, 29);

  button26 = gtk_button_new_with_mnemonic (_("hotels"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed3), button26, 216, 16);
  gtk_widget_set_size_request (button26, 74, 29);

  button27 = gtk_button_new_with_mnemonic (_("location de voiture"));
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed3), button27, 304, 16);
  gtk_widget_set_size_request (button27, 152, 29);

  button30 = gtk_button_new_with_mnemonic (_("mon compte"));
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed3), button30, 472, 16);
  gtk_widget_set_size_request (button30, 96, 29);

  ajouter_des_reclamations_ = gtk_button_new_with_mnemonic (_("ajouter des reclamations "));
  gtk_widget_show (ajouter_des_reclamations_);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_des_reclamations_, 192, 112);
  gtk_widget_set_size_request (ajouter_des_reclamations_, 208, 29);

  button33 = gtk_button_new_with_mnemonic (_("supprimer des reclamations "));
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed3), button33, 192, 152);
  gtk_widget_set_size_request (button33, 208, 29);

  button32 = gtk_button_new_with_mnemonic (_("modifier des reclamations "));
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed3), button32, 192, 192);
  gtk_widget_set_size_request (button32, 208, 29);

  retournergdr = gtk_button_new ();
  gtk_widget_show (retournergdr);
  gtk_fixed_put (GTK_FIXED (fixed3), retournergdr, 56, 80);
  gtk_widget_set_size_request (retournergdr, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retournergdr), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retournergdr, "clicked",
                    G_CALLBACK (on_retournergdr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_reclamations, gestion_des_reclamations, "gestion_des_reclamations");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button24, "button24");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button25, "button25");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button26, "button26");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button27, "button27");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button30, "button30");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, ajouter_des_reclamations_, "ajouter_des_reclamations_");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button33, "button33");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, button32, "button32");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, retournergdr, "retournergdr");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_des_reclamations, label4, "label4");

  return gestion_des_reclamations;
}

GtkWidget*
create_gestion_des_offres (void)
{
  GtkWidget *gestion_des_offres;
  GtkWidget *fixed4;
  GtkWidget *button34;
  GtkWidget *button35;
  GtkWidget *button36;
  GtkWidget *button37;
  GtkWidget *button38;
  GtkWidget *supprimer_des_catalogues;
  GtkWidget *ajouter_des_catalogues;
  GtkWidget *button41;
  GtkWidget *retournergdof;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;

  gestion_des_offres = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_offres), _("gestion des offres"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (gestion_des_offres), fixed4);

  button34 = gtk_button_new_with_mnemonic (_("offres"));
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed4), button34, 24, 16);
  gtk_widget_set_size_request (button34, 74, 29);

  button35 = gtk_button_new_with_mnemonic (_("voles"));
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed4), button35, 120, 16);
  gtk_widget_set_size_request (button35, 74, 29);

  button36 = gtk_button_new_with_mnemonic (_("hotels"));
  gtk_widget_show (button36);
  gtk_fixed_put (GTK_FIXED (fixed4), button36, 216, 16);
  gtk_widget_set_size_request (button36, 74, 29);

  button37 = gtk_button_new_with_mnemonic (_("location de voiture"));
  gtk_widget_show (button37);
  gtk_fixed_put (GTK_FIXED (fixed4), button37, 304, 16);
  gtk_widget_set_size_request (button37, 152, 29);

  button38 = gtk_button_new_with_mnemonic (_("mon compte"));
  gtk_widget_show (button38);
  gtk_fixed_put (GTK_FIXED (fixed4), button38, 472, 16);
  gtk_widget_set_size_request (button38, 96, 29);

  supprimer_des_catalogues = gtk_button_new_with_mnemonic (_("supprimer des catalogues "));
  gtk_widget_show (supprimer_des_catalogues);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer_des_catalogues, 192, 144);
  gtk_widget_set_size_request (supprimer_des_catalogues, 208, 29);

  ajouter_des_catalogues = gtk_button_new_with_mnemonic (_("ajouter des catalogues "));
  gtk_widget_show (ajouter_des_catalogues);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter_des_catalogues, 192, 104);
  gtk_widget_set_size_request (ajouter_des_catalogues, 208, 29);

  button41 = gtk_button_new_with_mnemonic (_("modifier des reclamations "));
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed4), button41, 192, 184);
  gtk_widget_set_size_request (button41, 208, 29);

  retournergdof = gtk_button_new ();
  gtk_widget_show (retournergdof);
  gtk_fixed_put (GTK_FIXED (fixed4), retournergdof, 32, 72);
  gtk_widget_set_size_request (retournergdof, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (retournergdof), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retournergdof, "clicked",
                    G_CALLBACK (on_retournergdof_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_offres, gestion_des_offres, "gestion_des_offres");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, button34, "button34");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, button35, "button35");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, button36, "button36");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, button37, "button37");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, button38, "button38");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, supprimer_des_catalogues, "supprimer_des_catalogues");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, ajouter_des_catalogues, "ajouter_des_catalogues");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, button41, "button41");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, retournergdof, "retournergdof");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_des_offres, label5, "label5");

  return gestion_des_offres;
}

GtkWidget*
create_gestion_des_reservations (void)
{
  GtkWidget *gestion_des_reservations;
  GtkWidget *fixed6;
  GtkWidget *button46;
  GtkWidget *button47;
  GtkWidget *button48;
  GtkWidget *button49;
  GtkWidget *button50;
  GtkWidget *retournerres;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;

  gestion_des_reservations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_reservations), _("gestion des reservations"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (gestion_des_reservations), fixed6);

  button46 = gtk_button_new_with_mnemonic (_("offres"));
  gtk_widget_show (button46);
  gtk_fixed_put (GTK_FIXED (fixed6), button46, 24, 16);
  gtk_widget_set_size_request (button46, 74, 29);

  button47 = gtk_button_new_with_mnemonic (_("voles"));
  gtk_widget_show (button47);
  gtk_fixed_put (GTK_FIXED (fixed6), button47, 120, 16);
  gtk_widget_set_size_request (button47, 74, 29);

  button48 = gtk_button_new_with_mnemonic (_("hotels"));
  gtk_widget_show (button48);
  gtk_fixed_put (GTK_FIXED (fixed6), button48, 216, 16);
  gtk_widget_set_size_request (button48, 74, 29);

  button49 = gtk_button_new_with_mnemonic (_("location de voiture"));
  gtk_widget_show (button49);
  gtk_fixed_put (GTK_FIXED (fixed6), button49, 304, 16);
  gtk_widget_set_size_request (button49, 152, 29);

  button50 = gtk_button_new_with_mnemonic (_("mon compte"));
  gtk_widget_show (button50);
  gtk_fixed_put (GTK_FIXED (fixed6), button50, 472, 16);
  gtk_widget_set_size_request (button50, 96, 29);

  retournerres = gtk_button_new ();
  gtk_widget_show (retournerres);
  gtk_fixed_put (GTK_FIXED (fixed6), retournerres, 32, 72);
  gtk_widget_set_size_request (retournerres, 96, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (retournerres), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retournerres, "clicked",
                    G_CALLBACK (on_retournerres_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_reservations, gestion_des_reservations, "gestion_des_reservations");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, button46, "button46");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, button47, "button47");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, button48, "button48");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, button49, "button49");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, button50, "button50");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, retournerres, "retournerres");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_des_reservations, label6, "label6");

  return gestion_des_reservations;
}

