/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_agent (void);
GtkWidget* create_gestion_de_clients (void);
GtkWidget* create_gestion_des_reclamations (void);
GtkWidget* create_gestion_des_offres (void);
GtkWidget* create_gestion_des_reservations (void);
