/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mywindow (void)
{
  GtkWidget *mywindow;
  GtkWidget *fixed1;
  GtkWidget *entryNom;
  GtkWidget *labelNom;
  GtkWidget *labelHello;
  GtkWidget *buttonHello;

  mywindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mywindow), _("myFirstExample"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (mywindow), fixed1);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 104, 32);
  gtk_widget_set_size_request (entryNom, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  labelNom = gtk_label_new (_("votre nom :"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 8, 40);
  gtk_widget_set_size_request (labelNom, 104, 17);

  labelHello = gtk_label_new (_("Hello !"));
  gtk_widget_show (labelHello);
  gtk_fixed_put (GTK_FIXED (fixed1), labelHello, 88, 176);
  gtk_widget_set_size_request (labelHello, 152, 32);

  buttonHello = gtk_button_new_with_mnemonic (_("say hello !"));
  gtk_widget_show (buttonHello);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonHello, 120, 104);
  gtk_widget_set_size_request (buttonHello, 120, 24);

  g_signal_connect ((gpointer) buttonHello, "clicked",
                    G_CALLBACK (on_buttonHello_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mywindow, mywindow, "mywindow");
  GLADE_HOOKUP_OBJECT (mywindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (mywindow, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (mywindow, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (mywindow, labelHello, "labelHello");
  GLADE_HOOKUP_OBJECT (mywindow, buttonHello, "buttonHello");

  return mywindow;
}

GtkWidget*
create_agent (void)
{
  GtkWidget *agent;
  GtkWidget *fixed2;
  GtkWidget *location_de_voiture;
  GtkWidget *hotels;
  GtkWidget *vols;
  GtkWidget *offre;
  GtkWidget *gestion_des_catalogues;
  GtkWidget *gestion_des_reclamations;
  GtkWidget *gestion_des_r__servations;
  GtkWidget *mon_compte;

  agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (agent), _("agent"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (agent), fixed2);

  location_de_voiture = gtk_button_new_with_mnemonic (_("location de voiture"));
  gtk_widget_show (location_de_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), location_de_voiture, 280, 16);
  gtk_widget_set_size_request (location_de_voiture, 184, 32);

  hotels = gtk_button_new_with_mnemonic (_("hotels"));
  gtk_widget_show (hotels);
  gtk_fixed_put (GTK_FIXED (fixed2), hotels, 192, 16);
  gtk_widget_set_size_request (hotels, 64, 32);

  vols = gtk_button_new_with_mnemonic (_("vols"));
  gtk_widget_show (vols);
  gtk_fixed_put (GTK_FIXED (fixed2), vols, 104, 16);
  gtk_widget_set_size_request (vols, 64, 32);

  offre = gtk_button_new_with_mnemonic (_("offre"));
  gtk_widget_show (offre);
  gtk_fixed_put (GTK_FIXED (fixed2), offre, 16, 16);
  gtk_widget_set_size_request (offre, 64, 32);

  gestion_des_catalogues = gtk_button_new_with_mnemonic (_("gestion des catalogues"));
  gtk_widget_show (gestion_des_catalogues);
  gtk_fixed_put (GTK_FIXED (fixed2), gestion_des_catalogues, 176, 120);
  gtk_widget_set_size_request (gestion_des_catalogues, 258, 29);

  gestion_des_reclamations = gtk_button_new_with_mnemonic (_("gestion des reclamations "));
  gtk_widget_show (gestion_des_reclamations);
  gtk_fixed_put (GTK_FIXED (fixed2), gestion_des_reclamations, 176, 160);
  gtk_widget_set_size_request (gestion_des_reclamations, 256, 29);
  gtk_button_set_focus_on_click (GTK_BUTTON (gestion_des_reclamations), FALSE);

  gestion_des_r__servations = gtk_button_new_with_mnemonic (_("gestion des r\303\251servations"));
  gtk_widget_show (gestion_des_r__servations);
  gtk_fixed_put (GTK_FIXED (fixed2), gestion_des_r__servations, 176, 200);
  gtk_widget_set_size_request (gestion_des_r__servations, 256, 29);

  mon_compte = gtk_button_new_with_mnemonic (_("mon compte"));
  gtk_widget_show (mon_compte);
  gtk_fixed_put (GTK_FIXED (fixed2), mon_compte, 488, 16);
  gtk_widget_set_size_request (mon_compte, 104, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (agent, agent, "agent");
  GLADE_HOOKUP_OBJECT (agent, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (agent, location_de_voiture, "location_de_voiture");
  GLADE_HOOKUP_OBJECT (agent, hotels, "hotels");
  GLADE_HOOKUP_OBJECT (agent, vols, "vols");
  GLADE_HOOKUP_OBJECT (agent, offre, "offre");
  GLADE_HOOKUP_OBJECT (agent, gestion_des_catalogues, "gestion_des_catalogues");
  GLADE_HOOKUP_OBJECT (agent, gestion_des_reclamations, "gestion_des_reclamations");
  GLADE_HOOKUP_OBJECT (agent, gestion_des_r__servations, "gestion_des_r__servations");
  GLADE_HOOKUP_OBJECT (agent, mon_compte, "mon_compte");

  return agent;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");

  return window3;
}

