/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowvolclient (void);
GtkWidget* create_windowvolagent (void);
GtkWidget* create_windowtreeag (void);
GtkWidget* create_windowtreeclient (void);
