/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowvolclient (void)
{
  GtkWidget *windowvolclient;
  GtkWidget *fixed1;
  GtkWidget *qp;
  GtkWidget *ville;
  GtkWidget *villea;
  GtkWidget *paysa;
  GtkWidget *qd;
  GtkObject *spinjour_adj;
  GtkWidget *spinjour;
  GtkObject *spinmois_adj;
  GtkWidget *spinmois;
  GtkObject *spinannee_adj;
  GtkWidget *spinannee;
  GtkWidget *date;
  GtkWidget *jr;
  GtkWidget *mo;
  GtkWidget *an;
  GtkWidget *voyageursvol;
  GtkObject *spinadulte_adj;
  GtkWidget *spinadulte;
  GtkObject *spinenfants_adj;
  GtkWidget *spinenfants;
  GtkWidget *heure;
  GtkWidget *adultetxt;
  GtkWidget *classse;
  GtkWidget *enfantstxt;
  GtkWidget *firstclass;
  GSList *firstclass_group = NULL;
  GtkWidget *paysd;
  GtkWidget *economique;
  GtkWidget *businessclass;
  GtkWidget *comboheure;
  GtkWidget *villecomboa;
  GtkWidget *recherchervol;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label26;
  GtkWidget *villecombo;
  GtkWidget *sucss;
  GtkWidget *back1_;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label25;
  GtkWidget *payscombo;
  GtkWidget *payscomboa;

  windowvolclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowvolclient), _("vol"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowvolclient), fixed1);

  qp = gtk_label_new (_("quelle provenance?:"));
  gtk_widget_show (qp);
  gtk_fixed_put (GTK_FIXED (fixed1), qp, 56, 80);
  gtk_widget_set_size_request (qp, 152, 16);

  ville = gtk_label_new (_("ville:"));
  gtk_widget_show (ville);
  gtk_fixed_put (GTK_FIXED (fixed1), ville, 336, 104);
  gtk_widget_set_size_request (ville, 56, 25);

  villea = gtk_label_new (_("ville:"));
  gtk_widget_show (villea);
  gtk_fixed_put (GTK_FIXED (fixed1), villea, 336, 176);
  gtk_widget_set_size_request (villea, 56, 25);

  paysa = gtk_label_new (_("pays:"));
  gtk_widget_show (paysa);
  gtk_fixed_put (GTK_FIXED (fixed1), paysa, 88, 176);
  gtk_widget_set_size_request (paysa, 56, 25);

  qd = gtk_label_new (_("quelle distination?:"));
  gtk_widget_show (qd);
  gtk_fixed_put (GTK_FIXED (fixed1), qd, 56, 144);
  gtk_widget_set_size_request (qd, 152, 16);

  spinjour_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  spinjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinjour_adj), 1, 0);
  gtk_widget_show (spinjour);
  gtk_fixed_put (GTK_FIXED (fixed1), spinjour, 88, 256);
  gtk_widget_set_size_request (spinjour, 40, 27);

  spinmois_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinmois_adj), 1, 0);
  gtk_widget_show (spinmois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinmois, 168, 256);
  gtk_widget_set_size_request (spinmois, 48, 27);

  spinannee_adj = gtk_adjustment_new (2019, 2019, 2025, 1, 10, 10);
  spinannee = gtk_spin_button_new (GTK_ADJUSTMENT (spinannee_adj), 1, 0);
  gtk_widget_show (spinannee);
  gtk_fixed_put (GTK_FIXED (fixed1), spinannee, 272, 256);
  gtk_widget_set_size_request (spinannee, 60, 27);

  date = gtk_label_new (_("date:"));
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed1), date, 64, 216);
  gtk_widget_set_size_request (date, 48, 16);

  jr = gtk_label_new (_("jour:"));
  gtk_widget_show (jr);
  gtk_fixed_put (GTK_FIXED (fixed1), jr, 48, 264);
  gtk_widget_set_size_request (jr, 41, 17);

  mo = gtk_label_new (_("mois:"));
  gtk_widget_show (mo);
  gtk_fixed_put (GTK_FIXED (fixed1), mo, 128, 264);
  gtk_widget_set_size_request (mo, 41, 17);

  an = gtk_label_new (_("ann\303\251e:"));
  gtk_widget_show (an);
  gtk_fixed_put (GTK_FIXED (fixed1), an, 224, 264);
  gtk_widget_set_size_request (an, 48, 17);

  voyageursvol = gtk_label_new (_("voyageurs:"));
  gtk_widget_show (voyageursvol);
  gtk_fixed_put (GTK_FIXED (fixed1), voyageursvol, 64, 304);
  gtk_widget_set_size_request (voyageursvol, 88, 25);

  spinadulte_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinadulte = gtk_spin_button_new (GTK_ADJUSTMENT (spinadulte_adj), 1, 0);
  gtk_widget_show (spinadulte);
  gtk_fixed_put (GTK_FIXED (fixed1), spinadulte, 192, 336);
  gtk_widget_set_size_request (spinadulte, 52, 27);

  spinenfants_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinenfants = gtk_spin_button_new (GTK_ADJUSTMENT (spinenfants_adj), 1, 0);
  gtk_widget_show (spinenfants);
  gtk_fixed_put (GTK_FIXED (fixed1), spinenfants, 424, 336);
  gtk_widget_set_size_request (spinenfants, 52, 27);

  heure = gtk_label_new (_("heure:"));
  gtk_widget_show (heure);
  gtk_fixed_put (GTK_FIXED (fixed1), heure, 368, 264);
  gtk_widget_set_size_request (heure, 41, 17);

  adultetxt = gtk_label_new (_("adulte:"));
  gtk_widget_show (adultetxt);
  gtk_fixed_put (GTK_FIXED (fixed1), adultetxt, 128, 344);
  gtk_widget_set_size_request (adultetxt, 57, 17);

  classse = gtk_label_new (_("classe :"));
  gtk_widget_show (classse);
  gtk_fixed_put (GTK_FIXED (fixed1), classse, 0, 0);
  gtk_widget_set_size_request (classse, 0, 0);

  enfantstxt = gtk_label_new (_("enfants:"));
  gtk_widget_show (enfantstxt);
  gtk_fixed_put (GTK_FIXED (fixed1), enfantstxt, 344, 344);
  gtk_widget_set_size_request (enfantstxt, 73, 16);

  firstclass = gtk_radio_button_new_with_mnemonic (NULL, _("First"));
  gtk_widget_show (firstclass);
  gtk_fixed_put (GTK_FIXED (fixed1), firstclass, 96, 416);
  gtk_widget_set_size_request (firstclass, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (firstclass), firstclass_group);
  firstclass_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (firstclass));

  paysd = gtk_label_new (_("pays:"));
  gtk_widget_show (paysd);
  gtk_fixed_put (GTK_FIXED (fixed1), paysd, 88, 104);
  gtk_widget_set_size_request (paysd, 56, 25);

  economique = gtk_radio_button_new_with_mnemonic (NULL, _("\303\251conomique"));
  gtk_widget_show (economique);
  gtk_fixed_put (GTK_FIXED (fixed1), economique, 456, 416);
  gtk_widget_set_size_request (economique, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (economique), firstclass_group);
  firstclass_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (economique));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (economique), TRUE);

  businessclass = gtk_radio_button_new_with_mnemonic (NULL, _("Business"));
  gtk_widget_show (businessclass);
  gtk_fixed_put (GTK_FIXED (fixed1), businessclass, 264, 416);
  gtk_widget_set_size_request (businessclass, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (businessclass), firstclass_group);
  firstclass_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (businessclass));

  comboheure = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboheure);
  gtk_fixed_put (GTK_FIXED (fixed1), comboheure, 424, 256);
  gtk_widget_set_size_request (comboheure, 133, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboheure), _("12:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboheure), _("14:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboheure), _("16:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboheure), _("18:00"));

  villecomboa = gtk_combo_box_entry_new_text ();
  gtk_widget_show (villecomboa);
  gtk_fixed_put (GTK_FIXED (fixed1), villecomboa, 384, 176);
  gtk_widget_set_size_request (villecomboa, 189, 29);

  recherchervol = gtk_button_new ();
  gtk_widget_show (recherchervol);
  gtk_fixed_put (GTK_FIXED (fixed1), recherchervol, 600, 464);
  gtk_widget_set_size_request (recherchervol, 98, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (recherchervol), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("R\303\251server"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox4), label26, FALSE, FALSE, 0);

  villecombo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (villecombo);
  gtk_fixed_put (GTK_FIXED (fixed1), villecombo, 384, 104);
  gtk_widget_set_size_request (villecombo, 189, 29);

  sucss = gtk_label_new ("");
  gtk_widget_show (sucss);
  gtk_fixed_put (GTK_FIXED (fixed1), sucss, 136, 456);
  gtk_widget_set_size_request (sucss, 304, 33);

  back1_ = gtk_button_new ();
  gtk_widget_show (back1_);
  gtk_fixed_put (GTK_FIXED (fixed1), back1_, 32, 24);
  gtk_widget_set_size_request (back1_, 80, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (back1_), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox3), label25, FALSE, FALSE, 0);

  payscombo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (payscombo);
  gtk_fixed_put (GTK_FIXED (fixed1), payscombo, 136, 104);
  gtk_widget_set_size_request (payscombo, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscombo), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscombo), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscombo), _("Italy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscombo), _("Usa"));

  payscomboa = gtk_combo_box_entry_new_text ();
  gtk_widget_show (payscomboa);
  gtk_fixed_put (GTK_FIXED (fixed1), payscomboa, 136, 176);
  gtk_widget_set_size_request (payscomboa, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscomboa), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscomboa), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscomboa), _("Italy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (payscomboa), _("Usa"));

  g_signal_connect ((gpointer) recherchervol, "clicked",
                    G_CALLBACK (on_recherchervol_clicked),
                    NULL);
  g_signal_connect ((gpointer) back1_, "clicked",
                    G_CALLBACK (on_back1__clicked),
                    NULL);
  g_signal_connect ((gpointer) payscombo, "changed",
                    G_CALLBACK (on_payscombo_changed),
                    NULL);
  g_signal_connect ((gpointer) payscomboa, "changed",
                    G_CALLBACK (on_payscomboa_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowvolclient, windowvolclient, "windowvolclient");
  GLADE_HOOKUP_OBJECT (windowvolclient, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowvolclient, qp, "qp");
  GLADE_HOOKUP_OBJECT (windowvolclient, ville, "ville");
  GLADE_HOOKUP_OBJECT (windowvolclient, villea, "villea");
  GLADE_HOOKUP_OBJECT (windowvolclient, paysa, "paysa");
  GLADE_HOOKUP_OBJECT (windowvolclient, qd, "qd");
  GLADE_HOOKUP_OBJECT (windowvolclient, spinjour, "spinjour");
  GLADE_HOOKUP_OBJECT (windowvolclient, spinmois, "spinmois");
  GLADE_HOOKUP_OBJECT (windowvolclient, spinannee, "spinannee");
  GLADE_HOOKUP_OBJECT (windowvolclient, date, "date");
  GLADE_HOOKUP_OBJECT (windowvolclient, jr, "jr");
  GLADE_HOOKUP_OBJECT (windowvolclient, mo, "mo");
  GLADE_HOOKUP_OBJECT (windowvolclient, an, "an");
  GLADE_HOOKUP_OBJECT (windowvolclient, voyageursvol, "voyageursvol");
  GLADE_HOOKUP_OBJECT (windowvolclient, spinadulte, "spinadulte");
  GLADE_HOOKUP_OBJECT (windowvolclient, spinenfants, "spinenfants");
  GLADE_HOOKUP_OBJECT (windowvolclient, heure, "heure");
  GLADE_HOOKUP_OBJECT (windowvolclient, adultetxt, "adultetxt");
  GLADE_HOOKUP_OBJECT (windowvolclient, classse, "classse");
  GLADE_HOOKUP_OBJECT (windowvolclient, enfantstxt, "enfantstxt");
  GLADE_HOOKUP_OBJECT (windowvolclient, firstclass, "firstclass");
  GLADE_HOOKUP_OBJECT (windowvolclient, paysd, "paysd");
  GLADE_HOOKUP_OBJECT (windowvolclient, economique, "economique");
  GLADE_HOOKUP_OBJECT (windowvolclient, businessclass, "businessclass");
  GLADE_HOOKUP_OBJECT (windowvolclient, comboheure, "comboheure");
  GLADE_HOOKUP_OBJECT (windowvolclient, villecomboa, "villecomboa");
  GLADE_HOOKUP_OBJECT (windowvolclient, recherchervol, "recherchervol");
  GLADE_HOOKUP_OBJECT (windowvolclient, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowvolclient, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowvolclient, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowvolclient, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowvolclient, villecombo, "villecombo");
  GLADE_HOOKUP_OBJECT (windowvolclient, sucss, "sucss");
  GLADE_HOOKUP_OBJECT (windowvolclient, back1_, "back1_");
  GLADE_HOOKUP_OBJECT (windowvolclient, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowvolclient, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowvolclient, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowvolclient, label25, "label25");
  GLADE_HOOKUP_OBJECT (windowvolclient, payscombo, "payscombo");
  GLADE_HOOKUP_OBJECT (windowvolclient, payscomboa, "payscomboa");

  return windowvolclient;
}

GtkWidget*
create_windowvolagent (void)
{
  GtkWidget *windowvolagent;
  GtkWidget *fixed3;
  GtkWidget *label8;
  GtkWidget *entrybuisad6;
  GtkWidget *entryfirstad7;
  GtkWidget *labelpays19;
  GtkWidget *labelville5;
  GtkWidget *labelville6;
  GtkWidget *labelpays7;
  GtkWidget *labelqp4;
  GtkWidget *entryecoad5;
  GtkWidget *ajoutvolagent;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label23;
  GtkWidget *villedajou;
  GtkWidget *villeaajou;
  GtkWidget *labelajoutsucc;
  GtkWidget *back2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label24;
  GtkWidget *paysdajou;
  GtkWidget *paysaajou;
  GtkWidget *label1pslc6;
  GtkWidget *buisp;
  GtkWidget *ecop;
  GtkWidget *firstp;

  windowvolagent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowvolagent), _("ajouter vol"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowvolagent), fixed3);

  label8 = gtk_label_new (_("quelle distination?:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 56, 144);
  gtk_widget_set_size_request (label8, 152, 16);

  entrybuisad6 = gtk_entry_new ();
  gtk_widget_show (entrybuisad6);
  gtk_fixed_put (GTK_FIXED (fixed3), entrybuisad6, 312, 352);
  gtk_widget_set_size_request (entrybuisad6, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrybuisad6), 8226);

  entryfirstad7 = gtk_entry_new ();
  gtk_widget_show (entryfirstad7);
  gtk_fixed_put (GTK_FIXED (fixed3), entryfirstad7, 496, 352);
  gtk_widget_set_size_request (entryfirstad7, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfirstad7), 8226);

  labelpays19 = gtk_label_new (_("pays:"));
  gtk_widget_show (labelpays19);
  gtk_fixed_put (GTK_FIXED (fixed3), labelpays19, 88, 104);
  gtk_widget_set_size_request (labelpays19, 56, 25);

  labelville5 = gtk_label_new (_("ville:"));
  gtk_widget_show (labelville5);
  gtk_fixed_put (GTK_FIXED (fixed3), labelville5, 336, 104);
  gtk_widget_set_size_request (labelville5, 56, 25);

  labelville6 = gtk_label_new (_("ville:"));
  gtk_widget_show (labelville6);
  gtk_fixed_put (GTK_FIXED (fixed3), labelville6, 336, 176);
  gtk_widget_set_size_request (labelville6, 56, 25);

  labelpays7 = gtk_label_new (_("pays:"));
  gtk_widget_show (labelpays7);
  gtk_fixed_put (GTK_FIXED (fixed3), labelpays7, 88, 176);
  gtk_widget_set_size_request (labelpays7, 56, 25);

  labelqp4 = gtk_label_new (_("quelle provenance?:"));
  gtk_widget_show (labelqp4);
  gtk_fixed_put (GTK_FIXED (fixed3), labelqp4, 56, 80);
  gtk_widget_set_size_request (labelqp4, 152, 16);

  entryecoad5 = gtk_entry_new ();
  gtk_widget_show (entryecoad5);
  gtk_fixed_put (GTK_FIXED (fixed3), entryecoad5, 144, 352);
  gtk_widget_set_size_request (entryecoad5, 64, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryecoad5), 8226);

  ajoutvolagent = gtk_button_new ();
  gtk_widget_show (ajoutvolagent);
  gtk_fixed_put (GTK_FIXED (fixed3), ajoutvolagent, 640, 424);
  gtk_widget_set_size_request (ajoutvolagent, 98, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajoutvolagent), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox1), label23, FALSE, FALSE, 0);

  villedajou = gtk_combo_box_entry_new_text ();
  gtk_widget_show (villedajou);
  gtk_fixed_put (GTK_FIXED (fixed3), villedajou, 384, 104);
  gtk_widget_set_size_request (villedajou, 189, 29);

  villeaajou = gtk_combo_box_entry_new_text ();
  gtk_widget_show (villeaajou);
  gtk_fixed_put (GTK_FIXED (fixed3), villeaajou, 384, 176);
  gtk_widget_set_size_request (villeaajou, 189, 29);

  labelajoutsucc = gtk_label_new ("");
  gtk_widget_show (labelajoutsucc);
  gtk_fixed_put (GTK_FIXED (fixed3), labelajoutsucc, 184, 416);
  gtk_widget_set_size_request (labelajoutsucc, 304, 33);

  back2 = gtk_button_new ();
  gtk_widget_show (back2);
  gtk_fixed_put (GTK_FIXED (fixed3), back2, 32, 24);
  gtk_widget_set_size_request (back2, 88, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (back2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox2), label24, FALSE, FALSE, 0);

  paysdajou = gtk_combo_box_entry_new_text ();
  gtk_widget_show (paysdajou);
  gtk_fixed_put (GTK_FIXED (fixed3), paysdajou, 136, 104);
  gtk_widget_set_size_request (paysdajou, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysdajou), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysdajou), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysdajou), _("Italy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysdajou), _("Usa"));

  paysaajou = gtk_combo_box_entry_new_text ();
  gtk_widget_show (paysaajou);
  gtk_fixed_put (GTK_FIXED (fixed3), paysaajou, 136, 176);
  gtk_widget_set_size_request (paysaajou, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysaajou), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysaajou), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysaajou), _("Italy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (paysaajou), _("Usa"));

  label1pslc6 = gtk_label_new (_("prix selon la classe :"));
  gtk_widget_show (label1pslc6);
  gtk_fixed_put (GTK_FIXED (fixed3), label1pslc6, 56, 288);
  gtk_widget_set_size_request (label1pslc6, 152, 16);

  buisp = gtk_label_new (_("buisness"));
  gtk_widget_show (buisp);
  gtk_fixed_put (GTK_FIXED (fixed3), buisp, 240, 352);
  gtk_widget_set_size_request (buisp, 73, 25);

  ecop = gtk_label_new (_("\303\211conomique"));
  gtk_widget_show (ecop);
  gtk_fixed_put (GTK_FIXED (fixed3), ecop, 40, 352);
  gtk_widget_set_size_request (ecop, 104, 24);

  firstp = gtk_label_new (_("first class"));
  gtk_widget_show (firstp);
  gtk_fixed_put (GTK_FIXED (fixed3), firstp, 424, 352);
  gtk_widget_set_size_request (firstp, 65, 25);

  g_signal_connect ((gpointer) ajoutvolagent, "clicked",
                    G_CALLBACK (on_ajoutvolagent_clicked),
                    NULL);
  g_signal_connect ((gpointer) back2, "clicked",
                    G_CALLBACK (on_back2_clicked),
                    NULL);
  g_signal_connect ((gpointer) paysdajou, "changed",
                    G_CALLBACK (on_paysdajou_changed),
                    NULL);
  g_signal_connect ((gpointer) paysaajou, "changed",
                    G_CALLBACK (on_paysaajou_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowvolagent, windowvolagent, "windowvolagent");
  GLADE_HOOKUP_OBJECT (windowvolagent, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowvolagent, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowvolagent, entrybuisad6, "entrybuisad6");
  GLADE_HOOKUP_OBJECT (windowvolagent, entryfirstad7, "entryfirstad7");
  GLADE_HOOKUP_OBJECT (windowvolagent, labelpays19, "labelpays19");
  GLADE_HOOKUP_OBJECT (windowvolagent, labelville5, "labelville5");
  GLADE_HOOKUP_OBJECT (windowvolagent, labelville6, "labelville6");
  GLADE_HOOKUP_OBJECT (windowvolagent, labelpays7, "labelpays7");
  GLADE_HOOKUP_OBJECT (windowvolagent, labelqp4, "labelqp4");
  GLADE_HOOKUP_OBJECT (windowvolagent, entryecoad5, "entryecoad5");
  GLADE_HOOKUP_OBJECT (windowvolagent, ajoutvolagent, "ajoutvolagent");
  GLADE_HOOKUP_OBJECT (windowvolagent, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowvolagent, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowvolagent, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowvolagent, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowvolagent, villedajou, "villedajou");
  GLADE_HOOKUP_OBJECT (windowvolagent, villeaajou, "villeaajou");
  GLADE_HOOKUP_OBJECT (windowvolagent, labelajoutsucc, "labelajoutsucc");
  GLADE_HOOKUP_OBJECT (windowvolagent, back2, "back2");
  GLADE_HOOKUP_OBJECT (windowvolagent, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowvolagent, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowvolagent, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowvolagent, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowvolagent, paysdajou, "paysdajou");
  GLADE_HOOKUP_OBJECT (windowvolagent, paysaajou, "paysaajou");
  GLADE_HOOKUP_OBJECT (windowvolagent, label1pslc6, "label1pslc6");
  GLADE_HOOKUP_OBJECT (windowvolagent, buisp, "buisp");
  GLADE_HOOKUP_OBJECT (windowvolagent, ecop, "ecop");
  GLADE_HOOKUP_OBJECT (windowvolagent, firstp, "firstp");

  return windowvolagent;
}

GtkWidget*
create_windowtreeag (void)
{
  GtkWidget *windowtreeag;
  GtkWidget *fixed4;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label48;
  GtkWidget *buttonsuppag11;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label50;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *buttonajouag9;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label52;
  GtkWidget *modifieragent;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label58;
  GtkWidget *label49;

  windowtreeag = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowtreeag), _("vol"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowtreeag), fixed4);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 32, 24);
  gtk_widget_set_size_request (button5, 80, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox5), label48, FALSE, FALSE, 0);

  buttonsuppag11 = gtk_button_new ();
  gtk_widget_show (buttonsuppag11);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsuppag11, 456, 384);
  gtk_widget_set_size_request (buttonsuppag11, 104, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonsuppag11), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox6), label50, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow2, 56, 136);
  gtk_widget_set_size_request (scrolledwindow2, 584, 174);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 544, 224);

  buttonajouag9 = gtk_button_new ();
  gtk_widget_show (buttonajouag9);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonajouag9, 136, 384);
  gtk_widget_set_size_request (buttonajouag9, 82, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonajouag9), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox8), label52, FALSE, FALSE, 0);

  modifieragent = gtk_button_new ();
  gtk_widget_show (modifieragent);
  gtk_fixed_put (GTK_FIXED (fixed4), modifieragent, 288, 384);
  gtk_widget_set_size_request (modifieragent, 88, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (modifieragent), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox13), label58, FALSE, FALSE, 0);

  label49 = gtk_label_new ("");
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed4), label49, 136, 456);
  gtk_widget_set_size_request (label49, 304, 33);

  g_signal_connect ((gpointer) buttonsuppag11, "clicked",
                    G_CALLBACK (on_buttonsuppag11_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonajouag9, "clicked",
                    G_CALLBACK (on_buttonajouag9_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifieragent, "clicked",
                    G_CALLBACK (on_modifieragent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowtreeag, windowtreeag, "windowtreeag");
  GLADE_HOOKUP_OBJECT (windowtreeag, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowtreeag, button5, "button5");
  GLADE_HOOKUP_OBJECT (windowtreeag, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowtreeag, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowtreeag, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowtreeag, label48, "label48");
  GLADE_HOOKUP_OBJECT (windowtreeag, buttonsuppag11, "buttonsuppag11");
  GLADE_HOOKUP_OBJECT (windowtreeag, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowtreeag, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowtreeag, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowtreeag, label50, "label50");
  GLADE_HOOKUP_OBJECT (windowtreeag, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (windowtreeag, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowtreeag, buttonajouag9, "buttonajouag9");
  GLADE_HOOKUP_OBJECT (windowtreeag, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowtreeag, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowtreeag, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowtreeag, label52, "label52");
  GLADE_HOOKUP_OBJECT (windowtreeag, modifieragent, "modifieragent");
  GLADE_HOOKUP_OBJECT (windowtreeag, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowtreeag, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowtreeag, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowtreeag, label58, "label58");
  GLADE_HOOKUP_OBJECT (windowtreeag, label49, "label49");

  return windowtreeag;
}

GtkWidget*
create_windowtreeclient (void)
{
  GtkWidget *windowtreeclient;
  GtkWidget *fixed5;
  GtkWidget *button12;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label53;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *buttonajoucli18;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label57;
  GtkWidget *buttonsuppcli16;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *modifierclient;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label59;

  windowtreeclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowtreeclient), _("vol"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowtreeclient), fixed5);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed5), button12, 32, 24);
  gtk_widget_set_size_request (button12, 80, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button12), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox9), label53, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 72, 112);
  gtk_widget_set_size_request (scrolledwindow1, 560, 254);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 544, 224);

  buttonajoucli18 = gtk_button_new ();
  gtk_widget_show (buttonajoucli18);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonajoucli18, 96, 408);
  gtk_widget_set_size_request (buttonajoucli18, 106, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonajoucli18), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox12), label57, FALSE, FALSE, 0);

  buttonsuppcli16 = gtk_button_new ();
  gtk_widget_show (buttonsuppcli16);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonsuppcli16, 432, 408);
  gtk_widget_set_size_request (buttonsuppcli16, 112, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonsuppcli16), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox10), label55, FALSE, FALSE, 0);

  label54 = gtk_label_new ("");
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 136, 456);
  gtk_widget_set_size_request (label54, 304, 33);

  modifierclient = gtk_button_new ();
  gtk_widget_show (modifierclient);
  gtk_fixed_put (GTK_FIXED (fixed5), modifierclient, 264, 408);
  gtk_widget_set_size_request (modifierclient, 88, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (modifierclient), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox14), label59, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonajoucli18, "clicked",
                    G_CALLBACK (on_buttonajoucli18_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuppcli16, "clicked",
                    G_CALLBACK (on_buttonsuppcli16_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierclient, "clicked",
                    G_CALLBACK (on_modifierclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowtreeclient, windowtreeclient, "windowtreeclient");
  GLADE_HOOKUP_OBJECT (windowtreeclient, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowtreeclient, button12, "button12");
  GLADE_HOOKUP_OBJECT (windowtreeclient, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowtreeclient, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowtreeclient, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowtreeclient, label53, "label53");
  GLADE_HOOKUP_OBJECT (windowtreeclient, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowtreeclient, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowtreeclient, buttonajoucli18, "buttonajoucli18");
  GLADE_HOOKUP_OBJECT (windowtreeclient, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowtreeclient, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowtreeclient, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowtreeclient, label57, "label57");
  GLADE_HOOKUP_OBJECT (windowtreeclient, buttonsuppcli16, "buttonsuppcli16");
  GLADE_HOOKUP_OBJECT (windowtreeclient, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowtreeclient, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowtreeclient, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowtreeclient, label55, "label55");
  GLADE_HOOKUP_OBJECT (windowtreeclient, label54, "label54");
  GLADE_HOOKUP_OBJECT (windowtreeclient, modifierclient, "modifierclient");
  GLADE_HOOKUP_OBJECT (windowtreeclient, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowtreeclient, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowtreeclient, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowtreeclient, label59, "label59");

  return windowtreeclient;
}

